### ISSUE TITLE
--query argument fails with: Unsupported operand type(s) for 'dict'

### ISSUE THREAD

**Issue by porg** [nk9/get_dropbox_link#12]
After the recent changes in 310b32c for:
- #3

## ✅ Filepath as the only argument works normal
```
$ get_dropbox_link.py ~/Dropbox/Public/test-2023-08-15a.txt 
https://www.dropbox.com/s/zk0z1wbblfh0e23/test-2023-08-15a.txt?dl=0
```
Note: Luckily I'm getting the classic `/s/` style links [again](https://github.com/nk9/get_dropbox_link/issues/11#issuecomment-1678982556).

## ❌ Custom arguments result in error
```
$ get_dropbox_link.py ~/Dropbox/Public/test-2023-08-15a.txt --query 'raw=1'
ERROR:root:unsupported operand type(s) for |: 'dict' and 'dict'
```

All possible permutations I tried failed with the same error:
- Arguments before/after filepath
- `--query` value in no quotes, single quotes, double quotes.

## Environment
- get_dropbox_link -- latest one: ad71584eb4c3
- macOS 11.7.8 Big Sur
- Python Env: Worked before, nothing changed AFAIK

**Comment by nk9** [comment]
This is an issue with a newer Python feature, [the union operator](https://peps.python.org/pep-0584/). In my testing, lower versions of Python 3.8 don't support this, whereas later versions of 3.8 and all versions of 3.9+ do.

I've changed to using the more broadly-supported `{**a, **b}` dict merging syntax.

**Comment by porg** [comment]
Tested and now worked with Python 3.11.4 on macOS 11.8.8 Big Sur.
