### ISSUE TITLE
Removing argument from URL by supplying `--query `arg=` argument as empty does not work anymore

### ISSUE THREAD

**Issue by porg** [nk9/get_dropbox_link#14]
The readme says:

> Note that you can remove an argument from the returned Dropbox link by marking it as empty:
>
> ```
> $ get_dropbox_link.py ~/Dropbox/file2.jpg --query 'raw=1&dl='
> https://www.dropbox.com/s/xxxx/file2.jpg?raw=1
> ```

Exactly that does not work anymore in the recent version.

Instead it puts the muted argument as the first argument with the value empty, like this:

 `https://www.dropbox.com/s/xxxx/file2.jpg?dl=&raw=1`

**Comment by nk9** [comment]
Thanks for pointing this out, I've fixed it so that the code now behaves like it says in the README.

**Comment by porg** [comment]
✅ Tested and it works fine:
- A muted argument now correctly gets removed in the output, regardless at which position it is supplied.
- `--query 'raw=1&dl='` and `--query 'dl=&raw=1'` both result in `raw=1` as the sole argument.
