### ISSUE TITLE
Beware that if you download the wrong way you get a minified Python script

### ISSUE THREAD

**Issue by porg** [nk9/get_dropbox_link#2]
![Github - Download source code file 1 the wrong way](https://github.com/nk9/get_dropbox_link/assets/737143/89874124-d42a-4a08-9668-c0e75864c426)

![Github - Download source code file 2 correctly](https://github.com/nk9/get_dropbox_link/assets/737143/eef8ef35-ad59-4b47-8d22-cb9ff36bb024)

**Comment by nk9** [comment]
Thanks for pointing this out, and for the pretty screenshots! I have refined the README instructions, and now include a link to download the whole repo as a zip file (which will also fetch the Automator Workflow for easy installation). So I think this should no longer be an issue.
