### ISSUE TITLE
Change default URL argument `?dl=0` to `?raw=1` and whitespace from ugly `%20` to better human readable `+`

### ISSUE THREAD

**Issue by porg** [nk9/get_dropbox_link#3]
## Thanks for offering this script!

Finally being able to assign a keyboard shortcut to the "Copy Dropbox Link" contextual menu item in Finder is a huge time saver.

## Feature Ideas

Realized the potential for other fully automated postprocessing features which for now I do:

1. manually — Change the default `?dl=0` argument to `?raw=1`

        ❌ https://www.dropbox.com/s/xxxx/cat.jpg?dl=0
        ✅ https://www.dropbox.com/s/xxxx/cat.jpg?raw=0

2. assisted  — Find/replace URL encoded space characters in TextEdit
   from the default ugly `%20` to the better human readable `+`

        ❌ https://www.dropbox.com/s/xxxx/preserve+whitespace+in+filenames+but+well+readable.jpg
        ✅ https://www.dropbox.com/s/xxxx/preserve%20whitespace%20in%20filenames%20but%20well%20readable.jpg

**Comment by porg** [comment]
# My attempts

## Outside of Python in the Shell by piping through sed

- ✅ All individual parts work
- ❌ But saving as an alias doesn't
  - I prefer having such small customization as aliases
  - But if escaping within the alias line is to difficult, I will do it as a standalone script in my path.
- ℹ️ And knowing how to do this in Python itself would also be cool. Input appreciated!

### ✅ Normal operation

	$ get_dropbox_link.py ~/Dropbox/Public/Notion-Hide-a-property-via-drag-n-drop.mp4 
	https://www.dropbox.com/s/•••/Notion-Hide-a-property-via-drag-n-drop.mp4?dl=0

### ✅ Testing the sed replacement

	$ echo 'https://www.dropbox.com/s/•••/Notion-Hide-a-property-via-drag-n-drop.mp4?dl=0' | sed 's|?dl=0|?raw=1|g'
	https://www.dropbox.com/s/•••/Notion-Hide-a-property-via-drag-n-drop.mp4?raw=1

### ✅ Running the postprocessing pipe for real

	$ get_dropbox_link.py ~/Dropbox/Public/Notion-Hide-a-property-via-drag-n-drop.mp4 | sed 's|?dl=0|?raw=1|g'
	https://www.dropbox.com/s/•••/Notion-Hide-a-property-via-drag-n-drop.mp4?raw=1

### ✅ Testing to pipe into less

	get_dropbox_link.py ~/Dropbox/Public/Notion-Hide-a-property-via-drag-n-drop.mp4 | less
	Less opens and shows the result.
	In case of submitting multiple filepath arguments less shows multiple lines just fine.


### ❌ But I fail to set this up as an alias (in `aliases.zsh` as I use [oh-my-zsh](https://ohmyz.sh) )

aliases.zsh contains:

	alias dropboxlink="get_dropbox_link.py \$1 | sed 's|?dl=0|?raw=1|g'"

Logging in afresh, running command alias:

	$ dropboxlink ~/Dropbox/Public/Notion-Hide-a-property-via-drag-n-drop.mp4 
	sed: RE error: illegal byte sequence
	usage: get_dropbox_link.py [-h] [--verbose] paths [paths ...]
	get_dropbox_link.py: error: the following arguments are required: paths


aliases.zsh contains:

	alias dropboxlink="get_dropbox_link.py \$1 | less"

Logging in afresh, running command alias:

	$ dropboxlink ~/Dropbox/Public/Notion-Hide-a-property-via-drag-n-drop.mp4         
	"/Users/•••/Dropbox/Public/Notion-Hide-a-property-via-drag-n-drop.mp4" may be a binary file.  See it anyway? usage: get_dropbox_link.py [-h] [--verbose] paths [paths ...]
	get_dropbox_link.py: error: the following arguments are required: paths
	# Pipe is stuck. Aborting with ⌃-C.

### My guesses

sed's complaint "illegal byte sequence" and your python script's complaint "may be a binary file" indicated that not the argument is piped through, but rather the file.

**Comment by nk9** [comment]
Thanks for opening the issue. Here is [the Dropbox docs page](https://help.dropbox.com/share/force-download) which discusses `raw` vs `dl`. It's not clear to me that `dl=1` would be a better default than `dl=0`, but it should be easy enough to add a configuration option to allow for either in post-processing.

As for replacing `%20` with `+`, I'm wary of making that change since it could corrupt some URLs. Does it successfully match URLs with literal plus characters in them, for example? Can you find any Dropbox documentation saying how they handle encoding spaces in shared URLs?

**Comment by porg** [comment]
Hi, glad to hear back from you that soon!
- I did not recommend those modifications for everybody!
- I rather just wanted to know how I need to modify the script to achieve my goals.
- Both mods work fine in practise for me for years now, I cannot give you the officials docs/references. They just work reliably and stable in all my Dropbox use cases over years now, that I can testify.
- I avoided literal plus symbols in URLs for the reason that despite `%20` being the only official encoding for the space character, but many webserver/website configs supporting `+` as a de facto standard too.

**Comment by porg** [comment]
- I avoided literal plus symbols in URLs for the reason that despite %20 being the only official encoding for the space character, but many webserver/website configs supporting + as a de facto standard too.

**Comment by nk9** [comment]
I've provided arguments for both of these features now. Give them a try and let me know if they work for you.

To answer my question from before: a URL with a plus in the filename is rendered as `file%2Bname.txt`. So plus characters sent in the URL are _always_ turned into spaces, and it's not ambiguous. So it's maybe possible for this to be the default, but I don't plan to change it. Seems safest to just provide the URLs as directly from Dropbox as possible.

**Comment by porg** [comment]
Thanks for you initiative!

Tested the current version:

1. In general the ideal synopsis for CLI apps is arguments first and file(s) last, because if you repeat a previous command (with arrow up) the cursor is at the end of the line, and then you can edit at the end, and the filepath(s) is what you will  most likely want to vary on the next invocation.
2. ✅ `--query raw=1`  worked fine

        $ get_dropbox_link.py  ~/Dropbox/Public/Click\ and\ lift\ finger\ 1a\ works.mp4 --query raw=1    
        https://www.dropbox.com/s/xxx/Click%20and%20lift%20finger%201a%20works.mp4?raw=1
        
3. ❌  `--plus-for-space`  fails

        get_dropbox_link.py  ~/Dropbox/Public/Click\ and\ lift\ finger\ 1a\ works.mp4 --plus-for-space
        ERROR:root:'PosixPath' object has no attribute 'with_stem'

**Comment by porg** [comment]
Using the customization arguments in the Automator script is real easy too:

#### Automator "Run Shell Script" per the original instruction is:

    $HOME/bin/get_dropbox_link.py "$@"

#### Modification, just add your desired arguments after the `"$@"`:

    $HOME/bin/get_dropbox_link.py "$@" --query raw=1
    
**Note:** When my proposal °1 from the previous post gets implemented, to put the file aruments at the last position, then simply put the formatting arguments before the `"$@"`.

**Comment by nk9** [comment]
Actually, it looks like the long option arguments (with `--`) would be best passed before the files. Certainly, they should work when passed before the file paths. I can change the README, but I don't believe a code change is necessary. Can you please confirm it's working this way for you now?

**Comment by porg** [comment]
Ad 1) Good news! Tested, and indeed argument `--query raw=1` worked fine before and after the files.

- Please update the README accordingly.

Ad 3) `--plus-for-space` though fails both when inserted before or after the filepath(s), and per each supplied file returns:

    ERROR:root:'PosixPath' object has no attribute 'with_stem'

**Comment by nk9** [comment]
Which version of Python are you running? It looks like [`with_stem`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.with_stem) is new in 3.9.

I can add a warning about the required Python version to the README.

**Comment by porg** [comment]
## My Python versions
```
$ which python
/usr/bin/python

$ python --version
Python 2.7.16

$ which python3
/usr/local/bin/python3

$ python3 --version
Python 3.11.2
```

## Which Python interpreter runs?

- Your script has a `#!/usr/bin/python3` shebang, so I guess it should run with python3.x
- Do I need to set something explicit again in the Automator environment that it really uses python3 ?

**Comment by porg** [comment]
- Btw, this feature is already implemented.
- The only reason why the issue is still open is because the README misses the corresponding update.

**Comment by nk9** [comment]
I've revised the feature to account for the [new Dropbox shared link style](https://www.dropboxforum.com/t5/Create-upload-and-share/New-URLs-for-shared-links-affecting-3rd-party-integrations/m-p/695272/highlight/true#M71062).

**Comment by porg** [comment]
## Interesting news

- Updated your script file to newest version.
- Tested with existing files and created some new files and dirs:
  - ~/Dropbox/Public/file-created-during-the-short-new-link-type-era.png
  - ~/Dropbox/Public/test-2023-08-15a.txt
  - ~/Dropbox/Tmp/test-2023-08-15b-Not-in-public-folder.txt
  - ~/Dropbox/Test-2023-08-15c-Dir/test-2023-08-15c-fresh-file-in-fresh-dir.txt
- Interestingly **all these (!)** now returned an "Old style" link, both via:
  - `get_dropbox_link.py`
  - Finder > Context menu > `Copy Dropbox Link` (official DropBox Finder extension)
- Dropbox seems to have totally (!) reverted this New Link API:
  - Not only for the special location `~/Dropbox/Public/` but seemingly everywhere, including also new files in existing directories and new files in new directories.
  - The rollback was so radical that even the "New link" style links (which were supposedly permalinks!) were rolled back (leaving a few forum posts of mine, whose editing timeframe closed meanwhile, with orphaned IMG links of this ill-fated era).
  - This can only be summarized as a big failure: Total rollback, not even a redirection for those few new link types which got out into the wild. This is diletantism of an early stage Startup (Dropbox anno 2007 maybe) but not an established top notch IT company in 2023. I would not have believed this to happen to such an IT giant, had I have not experienced it myself.

**Comment by porg** [comment]
Sadly I get a bug, created followup issue:
- #12

**Comment by nk9** [comment]
Thanks for the report. This has been resolved now.
