### ISSUE TITLE
get_dropbox_link.py CLI with multiple files returns all file URLs, but in Automator returns all URLs twice

### ISSUE THREAD

**Issue by porg** [nk9/get_dropbox_link#9]
## ✅ Running the script in the shell returns as many URLs as files you provided

```sh
$ get_dropbox_link.py ~/Dropbox/Public/Media-Library-UI-differences-2023-05-23-1818.png
https://www.dropbox.com/s/xxx/Media-Library-UI-differences-2023-05-23-1818.png?dl=0

$ get_dropbox_link.py ~/Dropbox/Public/Media-Library-UI-differences-2023-05-23-18*     
https://www.dropbox.com/s/xxx/Media-Library-UI-differences-2023-05-23-1818.png?dl=0
https://www.dropbox.com/s/yyy/Media-Library-UI-differences-2023-05-23-1821.png?dl=0
https://www.dropbox.com/s/zzz/Media-Library-UI-differences-2023-05-23-1823.png?dl=0
```

## ❌ But in Automator the list of selected files in Finder is twice in `$@` hence you also get the URLs twice

- This happens on macOS 11.7.6 Big Sur
- The Automator workflow is set to receive "files or folders" and passes it to the "Run Shell Script" block "as arguments".
- Through debugging/logging (see below) I could confirm that for some reason Automator passes on the whole file batch twice, e.g. "1, 2, 3, 1, 2, 3".

Shell Script in Automator
```sh

RESULT=$($HOME/bin/bin/get_dropbox_link.py "$@")

LOG="$HOME/Library/Logs/get_dropbox_link_debug.txt"

   echo INPUT: >> "$LOG"
     echo "$@" >> "$LOG"
          echo >> "$LOG"
  echo RESULT: >> "$LOG"
echo "$RESULT" >> "$LOG"
          echo >> "$LOG"
```

The log:

```
INPUT:
/Users/me/Dropbox/Public/Media-Library-UI-differences-2023-05-23-1821.png /Users/me/Dropbox/Public/Media-Library-UI-differences-2023-05-23-1818.png /Users/me/Dropbox/Public/Media-Library-UI-differences-2023-05-23-1823.png /Users/me/Dropbox/Public/Media-Library-UI-differences-2023-05-23-1821.png /Users/me/Dropbox/Public/Media-Library-UI-differences-2023-05-23-1818.png /Users/me/Dropbox/Public/Media-Library-UI-differences-2023-05-23-1823.png

RESULT:
https://www.dropbox.com/s/xxx/Media-Library-UI-differences-2023-05-23-1821.png?dl=0
https://www.dropbox.com/s/yyy/Media-Library-UI-differences-2023-05-23-1818.png?dl=0
https://www.dropbox.com/s/zzz/Media-Library-UI-differences-2023-05-23-1823.png?dl=0
https://www.dropbox.com/s/xxx/Media-Library-UI-differences-2023-05-23-1821.png?dl=0
https://www.dropbox.com/s/yyy/Media-Library-UI-differences-2023-05-23-1818.png?dl=0
https://www.dropbox.com/s/zzz/Media-Library-UI-differences-2023-05-23-1823.png?dl=0
```

## Followup
- Does any other user experience that too?
  - If so what macOS do you use?
- The fix seems easy to me: Cut `$@` in half in the shell script environment and then pass on that cleaned file list to `get_dropbox_link.py`
  - My fixing approach: Get the string length. Trim string to half length. Then pass it on.
  - Will report my progress.

**Comment by porg** [comment]
## I had a working solution to cut the string in half

```sh
LIST="$@"

LISTHALF=$(echo $LIST | cut -c -$(echo "scale=0; $(echo $LIST | wc -c) / 2" | bc))

RESULT=$($HOME/bin/bin/get_dropbox_link.py "$LISTHALF")

LOG="$HOME/Library/Logs/get_dropbox_link_debug.txt"

   echo INPUT: >> "$LOG"
    echo $LIST >> "$LOG"
          echo >> "$LOG"
  echo HALFED: >> "$LOG"
echo $LISTHALF >> "$LOG"
          echo >> "$LOG"
  echo RESULT: >> "$LOG"
  echo $RESULT >> "$LOG"
          echo >> "$LOG"

# echo "$RESULT"
```

## Only to notice this was not necessary, the solution is much simpler:

- Simply get rid of the top "Get Selected Finder Items" block.
- The "Run Shell Script" block receives the file list twice because the top "Workflow receives current files or folders" supplies the file list once (this is app neutral, in theory can also be elsewhere than Finder!) and the "Get Selected Finder Items" block just provided the same list again!

![Get Dropbox URL - Automator gets file list twice](https://github.com/nk9/get_dropbox_link/assets/737143/e44e2380-a797-46ef-a46d-0b9a53428cca)

## Followup

- Please change the Readme.md and your included Automator file accordingly.

**Comment by porg** [comment]
**Good news**: Both the newest `Readme.md` and also the newest included Automator file don't have that "Get Selected Finder Items" block anymore. Seems I had an outdated earlier version and had to learn it the hard way myself. 😉

**Comment by nk9** [comment]
Yep, I ran into the same issue and tweaked the code and README to fix it. Sorry you had to spend the time again, but hey: now you know a bit more about Automator, right? 😉

**Comment by porg** [comment]
Yes, and I learned how to cut a string in half in the Shell, haha!
